name: Build and deploy

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Setup coscmd and sdk
        run: sudo pip install coscmd

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Configure coscmd
        env:
          SECRET_ID: ${{ secrets.COS_SECRETID }}
          SECRET_KEY: ${{ secrets.COS_SECRETKEY }}
          BUCKET: ${{ secrets.HUGO_COS_BUCKET }}
          REGION: ${{ secrets.HUGO_COS_REGION }}
        run: coscmd config -a $SECRET_ID -s $SECRET_KEY -b $BUCKET -r $REGION

      - name: Upload to COS
        run: coscmd upload -rfs --delete public/ /

      - name: Flush CDN
        env:
          SECRET_ID: ${{ secrets.COS_SECRETID }}
          SECRET_KEY: ${{ secrets.COS_SECRETKEY }}
        run: |
          pip install --upgrade tencentcloud-sdk-python
          python scripts/flush-dns.py -i $SECRET_ID -k $SECRET_KEY      
      
      - name: Upload to COS
        env:
          BAIDU_TOKEN: ${{  secrets.BAIDU_TOKEN }}
        run: |
          pip install requests lxml
          python scripts/registry-to-baidu.py