name: Auto publish to static website

on:
  push:
    branches:
      - master

jobs:
  hugo-publish:
    name: publish content to static website
    runs-on: ubuntu-latest
    steps:
      - name: checkout blog repo
        uses: actions/checkout@v2

      - name: setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: latest
          extended: true

      - name: build content to public site
        working-directory: ./
        run: |
          make build
          hugo --minify --gc

      - name: install nodejs
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          
      - uses: manyuanrong/setup-ossutil@v2.0
        with:
          # endpoint 可以去oss控制台上查看
          endpoint: "	oss-cn-beijing.aliyuncs.com"
          # 使用我们之前配置在secrets里面的accesskeys来配置ossutil
          access-key-id: ${{ secrets.OSS_ACCESS_KEY_ID }}
          access-key-secret: ${{ secrets.OSS_ACCESS_KEY_SECRET }}
      
      - name: Deply To OSS
        run: |
          ossutil rm -r -f oss://jaegerdocs/
          ossutil cp -r -f public oss://jaegerdocs/
